import React, { useEffect, useState } from 'react';
import axios from 'axios';
import { ShieldAlert, CheckCircle, Clock } from 'lucide-react';



const severityBorderColor = (s) => {
  if (s === 'RED') return '#dc2626';
  if (s === 'YELLOW') return '#ca8a04';
  return '#16a34a';
};

const Alerts = () => {
  const [alerts, setAlerts] = useState([]);

  const fetchAlerts = async () => {
    try {
      const res = await axios.get('http://localhost:8000/api/v1/alerts');
      setAlerts(res.data);
    } catch (err) {
      console.error(err);
    }
  };

  useEffect(() => { fetchAlerts(); }, []);

  const resolveAlert = async (id) => {
    try {
      await axios.post(`http://localhost:8000/api/v1/alerts/${id}/resolve`);
      fetchAlerts();
    } catch (err) {
      console.error(err);
    }
  };

  const unresolved = alerts.filter(a => !a.is_approved);
  const resolved   = alerts.filter(a => a.is_approved);

  return (
    <div>
      <div style={{ display: 'flex', alignItems: 'center', gap: '16px', marginBottom: '8px' }}>
        <ShieldAlert size={36} color="#ef4444" />
        <div>
          <h1>Intelligence Alerts</h1>
          <p>Review and approve strategic threat alerts generated by the AI pipeline.</p>
        </div>
      </div>

      {/* Summary bar */}
      <div className="grid-3" style={{ marginBottom: '24px' }}>
        <div className="glass-panel" style={{ padding: '16px' }}>
          <h3>Total Alerts</h3>
          <p className="stat-value" style={{ fontSize: '28px' }}>{alerts.length}</p>
        </div>
        <div className="glass-panel" style={{ padding: '16px' }}>
          <h3>Pending Review</h3>
          <p className="stat-value" style={{ fontSize: '28px', color: '#dc2626' }}>{unresolved.length}</p>
        </div>
        <div className="glass-panel" style={{ padding: '16px' }}>
          <h3>Resolved</h3>
          <p className="stat-value" style={{ fontSize: '28px', color: '#16a34a' }}>{resolved.length}</p>
        </div>
      </div>

      <div className="glass-panel" style={{ minHeight: '400px' }}>
        {alerts.length === 0 ? (
          <div style={{ textAlign: 'center', padding: '64px', color: '#64748b' }}>
            <CheckCircle size={48} color="#22c55e" style={{ marginBottom: '16px', display: 'block', margin: '0 auto 16px' }} />
            <h3>No Active Alerts</h3>
            <p>Your competitive landscape is currently stable.</p>
          </div>
        ) : (
          <div style={{ display: 'flex', flexDirection: 'column', gap: '16px' }}>
            {alerts.map(alert => (
              <div key={alert.id} style={{
                padding: '20px 24px',
                background: alert.is_approved ? 'rgba(0,0,0,0.02)' : 'rgba(0,0,0,0.03)',
                borderRadius: '12px',
                borderLeft: `4px solid ${severityBorderColor(alert.severity)}`,
                display: 'flex',
                justifyContent: 'space-between',
                alignItems: 'center',
                gap: '16px',
                opacity: alert.is_approved ? 0.6 : 1,
                transition: 'opacity 0.3s'
              }}>
                <div style={{ flex: 1 }}>
                  <div style={{ display: 'flex', alignItems: 'center', gap: '12px', marginBottom: '6px' }}>
                    <span className={`badge ${alert.severity.toLowerCase()}`}>{alert.severity}</span>
                    <h3 style={{ margin: 0, color: alert.is_approved ? '#94a3b8' : '#0f172a', fontSize: '15px' }}>
                      {alert.title}
                    </h3>
                  </div>
                  <p style={{ margin: '0 0 8px 0', color: '#64748b', fontSize: '14px' }}>
                    {alert.description}
                  </p>
                  <div style={{ display: 'flex', alignItems: 'center', gap: '6px', color: '#64748b', fontSize: '12px' }}>
                    <Clock size={12} />
                    {new Date(alert.created_at).toLocaleString('en-US', { month: 'short', day: 'numeric', hour: '2-digit', minute: '2-digit' })}
                    &nbsp;· Competitor #{alert.competitor_id}
                  </div>
                </div>

                {!alert.is_approved ? (
                  <div style={{ display: 'flex', gap: '8px' }}>
                    <button
                      onClick={() => {
                        axios.post(`http://localhost:8000/api/v1/alerts/${alert.id}/email`)
                          .then((res) => window.alert(res.data.message))
                          .catch(err => window.alert('Failed to send email.'));
                      }}
                      style={{
                        padding: '10px 16px',
                        background: 'rgba(59, 130, 246, 0.08)',
                        border: '1px solid rgba(59, 130, 246, 0.3)',
                        color: '#2563eb',
                        borderRadius: '8px',
                        cursor: 'pointer',
                        fontWeight: '600',
                        whiteSpace: 'nowrap',
                        transition: 'all 0.2s'
                      }}>
                      📩 Email
                    </button>
                    <button
                      onClick={() => resolveAlert(alert.id)}
                      style={{
                        padding: '10px 20px',
                        background: 'transparent',
                        border: '1px solid #3b82f6',
                        color: '#3b82f6',
                        borderRadius: '8px',
                        cursor: 'pointer',
                        fontWeight: '600',
                        whiteSpace: 'nowrap',
                        transition: 'all 0.2s'
                      }}>
                      Approve & Resume Pipeline
                    </button>
                  </div>
                ) : (
                  <span style={{ display: 'flex', alignItems: 'center', gap: '4px', color: '#16a34a', fontWeight: 'bold', whiteSpace: 'nowrap' }}>
                    <CheckCircle size={16} /> Resolved
                  </span>
                )}
              </div>
            ))}
          </div>
        )}
      </div>
    </div>
  );
};

export default Alerts;
